### ISSUE TITLE
Updating for conda-build 3

### ISSUE THREAD

**Issue by jdblischak** [bgruening/conda_r_skeleton_helper#14]
The difference in the recipe produced by `conda skeleton cran` with conda-build 3 has some minor differences compared conda-build 2.

## meta.yaml

The meta.yaml is similar and the current helper script should already work. One new line that I don't fully understand is:

```
build:
  merge_build_host: True  # [win]
```

According to the [documentation](https://conda.io/docs/commands/build/conda-build.html):

> --merge-build-host Merge the build and host directories, even when host section or compiler jinja2 is present

## bld.bat

I don't think the helper script needs to edit bld.bat anymore. It is only 2 lines:

```
"%R%" CMD INSTALL --build .
IF %ERRORLEVEL% NEQ 0 exit 1
```

## build.sh

The biggest change is in build.sh.

```
#!/bin/bash

if [[ $target_platform =~ linux.* ]] || [[ $target_platform == win-32 ]] || [[ $target_platform == win-64 ]] || [[ $target_platform == osx-64 ]]; then
  export DISABLE_AUTOBREW=1
  mv DESCRIPTION DESCRIPTION.old
  grep -v '^Priority: ' DESCRIPTION.old > DESCRIPTION
  $R CMD INSTALL --build .
else
  mkdir -p $PREFIX/lib/R/library/udunits2
  mv * $PREFIX/lib/R/library/udunits2
fi
```

I think we'll want to keep the line `export DISABLE_AUTOBREW=1` since this prevents the R package from using homebrew to install package dependencies on macOS. I think we can remove the if/else since conda-forge is only building packages for linux, win-64, and osx-64 (I don't know what edge case this is catching).

**Comment by jdblischak** [comment]
I did some more investigating.

The `else` clause in `build.sh` is for noarch packages (`--use-noarch-generic`) [source](https://github.com/conda/conda-build/commit/0c1842ccf232e32bf6905949fab51c5fc50fbe82)

I know there is interest in making noarch R packages (see https://github.com/conda-forge/r-base-feedstock/pull/43), so we may want to leave this. Also, does the script need to decide if the package should be noarch and pass the appropriate flag? We could use the `NeedsCompilation` field from the DESCRIPTION file.

And the `DISABLE_AUTOBREW` is explained [here](https://github.com/conda/conda-build/commit/bc38a57297266311dc24bfc3728f4d4c47f4f4d1).

**Comment by bgruening** [comment]
I'm a little bit confused. Why is the skeleton builder not using the host section at all. Or do you see it?
I thought we need to use the host-section nowadays and more or less all build-dependencies are now host-dependencies.

**Comment by jdblischak** [comment]
I see the host section when using cb3:

```
$ conda build --version
conda-build 3.9.1
$ conda skeleton cran r-ggplot2
$ cat r-ggplot2/meta.yaml | grep -v '^#'
{% set version = '2.2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggplot2
  version: {{ version|replace("-", "_") }}

source:
  fn: ggplot2_2.2.1.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggplot2_2.2.1.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggplot2/ggplot2_2.2.1.tar.gz
  sha256: 5fbc89fec3160ad14ba90bd545b151c7a2e7baad021c0ab4b950ecd6043a8314

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-mass
    - r-digest
    - r-gtable >=0.1.1
    - r-lazyeval
    - r-plyr >=1.7.1
    - r-reshape2
    - r-scales >=0.4.1
    - r-tibble

  run:
    - r-base
    - r-mass
    - r-digest
    - r-gtable >=0.1.1
    - r-lazyeval
    - r-plyr >=1.7.1
    - r-reshape2
    - r-scales >=0.4.1
    - r-tibble

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ggplot2')"           # [not win]
    - "\"%R%\" -e \"library('ggplot2')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://ggplot2.tidyverse.org, https://github.com/tidyverse/ggplot2
  license: GPL-2 | file LICENSE
  summary: A system for 'declaratively' creating graphics, based on "The Grammar of Graphics".
    You provide the data, tell 'ggplot2' how to map variables to aesthetics, what graphical
    primitives to use, and it takes care of the details.
  license_family: GPL2
```

**Comment by bgruening** [comment]
Do we want to remove the build section, if not used?

**Comment by jdblischak** [comment]
> Do we want to remove the build section, if not used?

It's not really important to me, but I confirmed that the recipe will build if that section is missing. Our current helper scripts check line-by-line (and not by integer, but using the `for line in file` style), so it'd require some hacking (if I would write it at least) to check the `build:` line and the one after it to determine if it needs to be removed. How important is this to you?

**Comment by jdblischak** [comment]
It seems that the conda-forge linter doesn't like `merge_build_host`, so I think we should remove that.

https://github.com/conda-forge/staged-recipes/pull/5762/commits/4c76367bfec41b34797c96920984091e793a34f8
https://github.com/conda-forge/staged-recipes/pull/5762#issuecomment-385558569

**Comment by jdblischak** [comment]
Lastly, you've merged recipes with unfiltered `build.sh` files, e.g.

https://github.com/conda-forge/r-sessioninfo-feedstock/blob/master/recipe/build.sh

Do you still want the helper script to delete the following two lines?

```
mv DESCRIPTION DESCRIPTION.old
grep -v '^Priority: ' DESCRIPTION.old > DESCRIPTION
```

**Comment by bgruening** [comment]
@jdblischak lets leave this in. Thanks a lot John!

**Comment by bgruening** [comment]
> meta.yaml: An empty build: when their are no build dependencies

keep, it can have implications

> meta.yaml: merge_build_host

remove

> build.sh: Removing 'Priority' from DESCRIPTION

remove

**Comment by bgruening** [comment]
Thanks! :)

**Comment by bgruening** [comment]
relevant discussion and some good documentation here: https://github.com/conda-forge/conda-forge.github.io/pull/576/files#r184472132
