### ISSUE TITLE
Undefined Jinja2 variables remain (['cran_mirror', 'cran_mirror'])

### ISSUE THREAD

**Issue by nick-youngblut** [bgruening/conda_r_skeleton_helper#16]
I used `conda_r_skeleton_helper` to create a recipe for the `paco` R package (my first conda-forge contribution). Running `conda-build r-paco` worked fine on my computer:

```
conda-build               3.10.3                   py36_0    conda-forge
osx v10.11.6
```

...however, when I submitted the PR to conda-forge, circleci generated the following error:

```
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
rendering /home/conda/conda-recipes/r-paco for linux-64
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Computed that there are 1 distributions to build from 1 recipes
Resolved dependencies, will be built in the following order:
    r-paco-0.3.2-on-linux-64
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /opt/conda/conda_build_config.yaml
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from /opt/conda/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from config.variant
Attempting to finalize metadata for r-paco
INFO:conda_build.metadata:Attempting to finalize metadata for r-paco
Undefined Jinja2 variables remain (['cran_mirror', 'cran_mirror']).  Please enable source downloading and try again.
Exited with code 1
```

Should I change {{'cran_mirror'}} to a specific mirror (eg., "https://cloud.r-project.org")? Should I add "cran_mirror" to the jinja template somehow? 

I can't find any documentation on this issue, which is surprising, given that all users would probably run into this problem when using `conda_r_skeleton_helper`.

**Comment by bgruening** [comment]
Hi @nick-youngblut, cran_mirror will get a sane default in one of the next conda-build version. For the time being, please set it manually.

**Comment by nick-youngblut** [comment]
Ok. Thanks for letting me know! I just saw in some of the other `conda-forge` PRs that developers have added `{% set cran_mirror = 'https://cran.r-project.org' %}` to the `meta.yaml` file. I did the same, which fixed the cirleci error.

**Comment by jdblischak** [comment]
@nick-youngblut Sorry for the inconvenience. I also had this same problem in the past. Unfortunately conda-build is a moving target these days, so it's difficult to make this script keep up with the changes. As @bgruening mentioned, this is not desired behavior for conda-build, so it will be fixed soon. Make sure to run `conda update conda-build` before your next submission.

And congrats on your first merged PR to staged recipes! May it be the first of many :-)
