### ISSUE TITLE
Add sed, coreutils in meta.yaml when make is present

### ISSUE THREAD

**Issue by isuruf** [bgruening/conda_r_skeleton_helper#19]
https://github.com/conda/conda-build/pull/2963

**Comment by jdblischak** [comment]
@isuruf Could you please provide some more context? For example:

* What do you think of the suggestion in conda/conda-build#2963 to add these to the r-base recipe?

* Do you have suggestions for how to detect if make is needed? I'm not overly keen in trying to duplicate the CRAN skeleton (e.g. [L1051](https://github.com/conda/conda-build/blob/6d73b66acba5fc9cdba996e899ca95e3f1e7fb20/conda_build/skeletons/cran.py#L1051)):



```
                need_make = True if any((need_autotools, need_f, need_cxx, need_c)) else \
                    any([f.name.lower().endswith(('/makefile', '/makevars'))
                        for f in tf])
```

My only idea would be to check the field `NeedsCompilation` from the DESCRIPTION file on CRAN. However, in my opinion, this helper script is for making minor adjustments to the standard CRAN skeleton. If we get to the point where we need to start making more complex decisions that duplicate parts of the CRAN skeleton, I'd prefer to try and add a `--conda-forge` flag (or something similar) directly to conda-build.

**Comment by isuruf** [comment]
> What do you think of the suggestion in conda/conda-build#2963 to add these to the r-base recipe?

Since we haven't been able to build r-base on windows for a while, we can't add these to the r-base recipe. Even if we could, I'm not sure as we'll be adding dependencies for no reason. We don't add the compiler, so why add sed and coreutils?

> Do you have suggestions for how to detect if make is needed?

This is easy. Just check whether there's a `{{posix}}make` in the meta.yaml created by conda skeleton cran.
