### ISSUE TITLE
The DESCRIPTION text gets removed from the recipes.

### ISSUE THREAD

**Issue by mingwandroid** [bgruening/conda_r_skeleton_helper#25]
Compare:

https://github.com/conda-forge/r-ape-feedstock/blob/master/recipe/meta.yaml vs https://github.com/AnacondaRecipes/r-ape-feedstock/blob/master/recipe/meta.yaml

AR version has "# The original CRAN metadata for this package was: .."

This block is deliberately emited and IMHO should not be elided in the aim (I guess?) of smaller recipes. It should not be elided because it alllows for reproduction of the recipe at a later date and also would ease implementing a `conda skeleton --update` feature (my thinking here is to do a diff of the old recipe (with our modifications) vs the old recipe recreated exactly from the DESCRIPTION, then apply those metadata diffs to the updated recipe.

**Comment by jdblischak** [comment]
@mingwandroid I would have no issue with this, but I am pretty sure the conda-forge linter would complain. The decision to remove the CRAN metadata from the recipes was made before I got involved with conda-forge.

@bgruening Would you be able to provide some more context on the original decision? What are your thoughts on including the CRAN metadata in conda-forge recipes?

**Comment by bgruening** [comment]
There is not much context, formally on bioconda people decided to remove all comments to keep the recipe clean. I have no problems with including this additional version if useful.

**Comment by jdblischak** [comment]
@mingwandroid Here's a test case PR. I added back the original CRAN metadata, and the recipe passed the conda-forge linter.

https://github.com/conda-forge/staged-recipes/pull/7128

**Comment by jdblischak** [comment]
Quick update: both r-bfa (https://github.com/conda-forge/staged-recipes/pull/7172/files) and r-esabcv (https://github.com/conda-forge/staged-recipes/pull/7128) includes the original CRAN metadata, passed the linter, and were merged

**Comment by mingwandroid** [comment]
Great news, thanks @jdblischak!
