### ISSUE TITLE
noarch packages fail the staged-recipes linter

### ISSUE THREAD

**Issue by jdblischak** [bgruening/conda_r_skeleton_helper#27]
Our helper script currently creates recipes that fail the staged-recipes linter for any CRAN package that does not need to be compiled. This is because we added support for noarch in PR #24, which I did by [suggestion](https://github.com/regro/cf-scripts/pull/394#issuecomment-438405035) from @isuruf. The purpose of this helper script is to create recipes according to conda-forge requirements, so we need to fix this. Here are the options I see:
1. Update the helper script to remove all lines with selectors for noarch recipes
1. Update the linter
1. Remove noarch support
1. Update the conda-build skeleton to remove selectors when `--use-noarch-generic` is set

Thoughts on how to proceed? @isuruf @bgruening @cbrueffer @dbast

Examples:
* A recipe I recently submitted that is currently failing the linter: https://github.com/conda-forge/staged-recipes/pull/7128#issuecomment-442990026
* A recipe where @dbast [removed the noarch support](https://github.com/conda-forge/staged-recipes/compare/88d199d0bfcb936ccdd035609ad88c77f6a91ace..1c06165304afb917bccf3ceef2a1cb0d546f48cb) in order to pass the staged-recipes linter

**Comment by isuruf** [comment]
My vote is on 2.

**Comment by bgruening** [comment]
@jdblischak I think we can simply remove the `     - {{posix}}zip               # [win] ` this should not be needed anymore.

**Comment by bgruening** [comment]
https://github.com/conda-forge/r-iml-feedstock/blob/master/recipe/meta.yaml is already fixed.
