### ISSUE TITLE
R packages on Github

### ISSUE THREAD

**Issue by Btibert3** [bgruening/conda_r_skeleton_helper#35]
How would we go about adding an R package that is currently on github?  It is very common to use `devtools::install_github` and there are instances where some maintainers of R packages do not want to go down the path of getting it published on CRAN.  

I would love to help build out the R ecosystem in conda, so any help/guidance will be much appreciated.

**Comment by bgruening** [comment]
@Btibert3 welcome! Glad to see more and more people interested in Conda :)

This helper script is just a very tiny extension around the real `conda skeleton cran` to make it fit conda-forge guidelines. So my call would be to ingrate the `devtools::install_github` functionallity in the long run into `conda skeleton`. For the time being, we can play around with some prototypes here if you like.

**Comment by bgruening** [comment]
@Btibert3 have a look at: https://github.com/conda/conda-build/blob/master/conda_build/skeletons/cran.py

**Comment by jdblischak** [comment]
@Btibert3 You can create a conda recipe for an R package on GitHub by passing the repository URL to `conda skeleton cran`. The main requirements are that the package is in the root of the repository and that it has at least one tagged release.

**Comment by Btibert3** [comment]
Thanks so much @jdblischak @bgruening .  Let me pour over this, exciting stuff!

**Comment by brendanf** [comment]
I just tried running the python version of the script on an R package from github, by putting the URL of the git repository in `packages.txt`.  Everything worked up until here:
https://github.com/bgruening/conda_r_skeleton_helper/blob/2cb70d83278cb388b2d5ec87195386117a096088/run.py#L82-L87 I ran it in python interactively and changed `fn` to the actual name of the package after running `conda skeleton cran` and before defining `meta_fname`, and the rest of the script finished without issue.  So maybe a minor change to check if the package name is a URL and then parse out the repository name is all that would be required.

**Comment by jdblischak** [comment]
@brendanf Are you planning on submitting the GitHub-only R package to conda-forge? This wrapper script only serves the purpose of meeting conda-forge's formatting requirements. You can run `conda skeleton cran <GitHub URL>` independent of this script.

You are welcome to submit a PR to add support for GitHub URLs. However, note that I actively discourage the addition of GitHub only packages to conda-forge unless there is a good reason the package cannot be submitted to CRAN (see discussion in https://github.com/conda-forge/conda-forge.github.io/issues/668). CRAN packages are regularly checked with `R CMD check` on multiple platforms and the conda-forge tickbot automatically sends a PR when any CRAN package is updated (and thus they are easier to maintain). Therefore I'm ok that this helper script doesn't support GitHub URLs.

**Comment by brendanf** [comment]
@jdblischak In this case it was in fact my own package, which is not ready for release on CRAN, but which I need to test partly in a conda environment on a cluster.  I was using the script to clean up the recipe from `conda build skeleton cran` before building it and putting it in my personal channel. (And also I was curious what would happen.)

I happened to be on this issue page to file the unrelated #39, and saw this issue, so I thought I would add my experience.  For now it's not a priority for me, since I tend to agree that it's best to stick to CRAN releases on conda-forge unless there's a compelling reason not to.
