### ISSUE TITLE
packages.txt

### ISSUE THREAD

**Issue by Juke34** [bgruening/conda_r_skeleton_helper#45]
Naive question, should I keep what is already present in the packages.txt
'''
r-tilegramsr
r-udunits2
r-usethis
'''
and add my package, or should I replace what is already there?

**Comment by jdblischak** [comment]
The script creates a recipe for each package listed in `packages.txt`. It'll be quicker if you only include the package(s) you need. But the worse case is that it will take extra time and create recipes for those existing packages as well.

**Comment by Juke34** [comment]
Ok what is already there are just examples, I don't need it

**Comment by jdblischak** [comment]
> Ok what is already there are just examples, I don't need it

Right, those are examples. We also use them for interactive testing when we need to make an update to the helper script.
