### ISSUE TITLE
Helper ask to install conda-build

### ISSUE THREAD

**Issue by yvanlebras** [bgruening/conda_r_skeleton_helper#50]
Hi wonder Björn,

It appears that we have some trouble with the conda_r_skeleton_helper as using it, there is a message asking to install conda-build. Do you know if this can be due to a misconfig on our computers ? Or maybe there is something to care about on the helper side ?

**Comment by bgruening** [comment]
You need to have conda-build installed. So try `conda install conda-build`

**Comment by yvanlebras** [comment]
of course, conda-build is already installed (or at least, it seems) ;)

**Comment by yvanlebras** [comment]
Nothing appears.... Looking at the .bashrc, the PATH for conda-build is ok `/home/pndb-cr/miniconda3/bin:$PATH` ... but when sourcing the .bashrc, executin conda-build is not working. Executing conda build works. Do you make a mistake beetween conda-build and conda build command ?
