### ISSUE TITLE
Windows build fails for r-bipartitemodularitymaximization

### ISSUE THREAD

**Issue by ezherman** [bgruening/conda_r_skeleton_helper#59]
Hi, thank you for creating this resource! I tried following the instructions to get the R package [BipartiteModularityMaximization](https://cran.r-project.org/web/packages/BipartiteModularityMaximization/index.html) onto conda-forge. However, the windows build failed (see https://github.com/conda-forge/staged-recipes/pull/22460). I am sadly out of my depth here - would you be able to provide any thoughts on how I could fix this failure? I did not develop the R package, I'm only using it in one of my workflows.

Thanks in advance!

**Comment by bgruening** [comment]
@ezherman I don't have a windows machine available to debug. The recipe looks good to me. Maybe there are some quirks that you need to do to compile it on windows. Sorry, but maybe its better to ask for help in your conda-forge PR and ping the r-team or windows team there.

**Comment by jdblischak** [comment]
Agreed with @bgruening. Issues in this repository are to report any problems in the generated recipe, particularly if the linter fails. In this case, everything looks fine.

Unfortunately more complex packages need additional troubleshooting that can't be anticipated beforehand, especially for packages that require compilation. This discussion takes place on the staged-recipes PR itself. I reviewed the Windows build log and commented on your PR with some advice on what to try next.

**Comment by bgruening** [comment]
Thanks @jdblischak!

**Comment by mfansler** [comment]
FYI, there is a global recipe patch suggested, just hasn't merged yet: https://github.com/conda/conda-build/pull/4786

Basically, Conda Forge has gotten stricter in testing linked libraries, and since the R.dll is in an atypical location it isn't picked up correctly. We might want to consider adding the patch here in the meantime to alleviate confusion on new submissions.

**Comment by cmkobel** [comment]
I'm having the exact same problem, I think. 

Could anyone direct me on how to solve this problem?

---
Technical info: 
"ERROR (r-chnosz,lib/R/library/CHNOSZ/libs/x64/CHNOSZ.dll): $RPATH/R.dll not found in packages, sysroot(s) nor the missing_dso_whitelist."

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=924527&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=7c0f8eae-6d6f-51bf-636f-73a1a7fb1bc4&l=1747
