### ISSUE TITLE
All run scripts fail on conda version 24

### ISSUE THREAD

**Issue by dansmith01** [bgruening/conda_r_skeleton_helper#61]
The scripts are checking for a version prefix of '3', and refuse to run for anyone using the latest version of conda (24).

**Comment by jdblischak** [comment]
@dansmith01 Thanks for reporting this problem! Please pull the latest from the repository and try again. It should work now with the latest conda and conda-build (but please let us know if not)

**Comment by dansmith01** [comment]
@jdblischak Great! Thanks for fixing that!

**Comment by jdblischak** [comment]
All credit goes to @mfansler. I just clicked on the merge button 😄 Glad it's working again!
